// src/ui/src/app/poduct-catalog/components/product-preview/product-preview.component.ts
import { Component, Input } from '@angular/core';
import { ProductForListModel } from '../../models/product-for-list-model';
import { CommonModule } from '@angular/common';
import { ShoppingCartService } from '../../../shopping-cart/shopping-cart.services';
import { StorageService } from '../../../core/services/storage-service';

@Component({
  selector: 'product-preview',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './product-preview.component.html',
  styleUrl: './product-preview.component.css',
})
export class ProductPreviewComponent {
  @Input() product: ProductForListModel;
  constructor(
    private shoppingCartService: ShoppingCartService,
    private storageService: StorageService,
  ) {}

  addToCart() {
    this.shoppingCartService
      .addCartItem({
        productId: this.product.id,
        quantity: 3,
        productName: this.product.name,
        productImageUrl: this.product.imageUrl!,
      })
      ?.subscribe((res) => {});
  }
}

<div class="card">
  <img *ngIf="product.imageUrl" src="{{ product.imageUrl }}" class="card-img-top" alt="..." style="padding: 40px" />
  <img *ngIf="!product.imageUrl" src="assets/images/cubes.png" class="card-img-top" alt="..." style="padding: 40px" />
  <h5 class="card-header">{{ product.name }}</h5>
  <div class="card-body">
    <p class="card-text mb-3">
      <strong>Unit Price:</strong> ${{ product.unitPrice.toFixed(2) }}
    </p>
    <span class="btn btn-primary mx-1" *ngFor="let cat of product.categories.split(',')">
      {{ cat }}
    </span>
  </div>
  <div class="card-footer">
    <product-cart-control [cartItem]="productForModel" *ngIf="product.isAvailable" />
    <button class="btn btn-danger" *ngIf="isAdmin" (click)="deleteProduct()">Delete</button>
    <h4 *ngIf="!product.isAvailable" class="text-danger">Currently Unavailable</h4>
  </div>
</div>

// src/ui-admin/src/product-catalog/components/product-preview.tsx
import type { ProductForListModel } from "./models/product-for-list-model";
import catalogServices from "../services/catalog.services";

export function ProductPreview({ product, onDeleted }: Readonly<{ product: ProductForListModel, onDeleted: () => void }>) {
    function deleteProduct() {
        catalogServices.deleteProduct(product.id)
            .then(res => {
                onDeleted();

            }, err => {

            });
    }

    return (
        <div className="col-lg-3 col-md-4 col-sm-6 mb-4">
            <div className="card">
                {product.imageUrl != null
                    ? <img src={product.imageUrl} className="card-img-top" alt="..." style={{ padding: '40px' }} />
                    : <img src='assets/images/cubes.png' className="card-img-top" alt="..." style={{ padding: '40px' }} />
                }

                <h5 className="card-header">{product.name}</h5>

                <div className="card-body">
                    <p className="card-text mb-3">
                        <strong>Unit Price:</strong> ${product.unitPrice.toFixed(2)}
                    </p>
                    <span className="btn btn-primary mx-1" >
                        {product.categories.split(',').map(cat => cat)}
                    </span>
                </div>

                <div className="card-footer">
                    <button className="btn btn-danger" onClick={deleteProduct}>Delete</button>
                    {!product.isAvailable && <h4 className="text-danger">Currently Unavailable</h4>}

                </div >
            </div >
        </div >
    );
}
