// src/ui/src/app/app.component.ts
import { Component } from "@angular/core";
import { RouterLink, RouterOutlet } from "@angular/router";
import { AuthService } from "./authentication/services/authentication.service";
import { AppServicesProvider } from "./core/services/app-services.provider";
import { IdentityControlsComponent } from "./authentication/components/authentication-landing/identity-controls/identity-controls.component";
import { LoadingSpinnerComponent } from "./core/components/loading-spinner/loading-spinner.component";

@Component({
  selector: "app-root",
  standalone: true,
  imports: [RouterOutlet, IdentityControlsComponent, LoadingSpinnerComponent],
  templateUrl: "./app.component.html",
  styleUrl: "./app.component.css",
})
export class AppComponent extends AppServicesProvider {
  constructor(
    authService: AuthService
  ) {
    super();

    authService.configure();
  }

  itemsCount = 0;
  ngOnInit() { }
}

<loading-spinner />
<div class="min-vh-100 bg-light">
  <!-- Navigation Bar -->
  <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <div class="container">
      <a class="navbar-brand fw-bold" href="#">Amazon</a>

      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarNav">
        <identity-controls class="navbar-nav ms-auto" />
      </div>
    </div>
  </nav>

  <div class="container my-5">
    <router-outlet></router-outlet>
  </div>
</div>

// src/ui-admin/src/App.tsx
import "./App.css";
import LoadingSpinner from "./core/components/loading-spinner/loading-spinner";
import IdentityControls from "./identity-controls";
import ProductList from "./product-catalog/components/products-list";

function App() {
  return (
    <>
      <LoadingSpinner />
      <div className="min-vh-100 bg-light">
        <nav className="navbar navbar-expand-lg navbar-dark bg-primary">
          <div className="container">
            <a className="navbar-brand fw-bold" href="#">
              Amazon
            </a>

            <button
              className="navbar-toggler"
              type="button"
              data-bs-toggle="collapse"
              data-bs-target="#navbarNav"
              aria-controls="navbarNav"
              aria-expanded="false"
              aria-label="Toggle navigation"
            >
              <span className="navbar-toggler-icon"></span>
            </button>

            <div className="collapse navbar-collapse" id="navbarNav">
              <IdentityControls isAuthenticated={false} />
            </div>
          </div>
        </nav>

        <div className="container my-5">
          <ProductList />
          {/* <router-outlet></router-outlet> */}
        </div>
      </div>
    </>
  );
}

export default App;
