// src/ui/src/app/authentication/components/authentication-landing/identity-controls/identity-controls.component.ts
import {CommonModule} from "@angular/common";
import {Component} from "@angular/core";
import {AuthenticatedUser} from "../../../models/authenticated-user.model";
import {AuthService} from "../../../services/authentication.service";
import {environment} from "../../../../../environments/environment";
import {OAuthService} from "angular-oauth2-oidc";

@Component({
  selector: "identity-controls",
  standalone: true,
  imports: [CommonModule],
  templateUrl: "./identity-controls.component.html",
})
export class IdentityControlsComponent {
  authenticatedUser: AuthenticatedUser | null;

  constructor(
    private authService: AuthService,
    private oauthService: OAuthService,
  ) {
    authService.userSubject.subscribe((u) => {
      this.authenticatedUser = u;
    });
  }

  startOAuthLogin() {
    this.authService.initiateCodeFlow();
  }

  navigateToSignUp() {
    const appUrlBase = window.location.origin;

    window.location.href = `${environment.authenticationBaseUrl}/Account/RegisterCustomer?ReturnUrl=${appUrlBase}/auth/signin`;
  }

  logout() {
    this.authService.logoutCurrentUser();
  }

  refreshToken() {
    this.authService.refreshToken();
  }
}

<li class="nav-link">
  <shopping-cart [style]="'mini'" />
</li>

<ng-container *ngIf="!authenticatedUser">
  <li class="nav-link">
    <button class="btn btn-outline-light ms-2" type="button" (click)="startOAuthLogin()">
      Login
    </button>

    <button class="btn btn-outline-light ms-2" type="button" (click)="navigateToSignUp()">
      Sign up
    </button>
  </li>
</ng-container>

<ng-container *ngIf="authenticatedUser">

  <li class="nav-link">
    <span>{{ authenticatedUser.email }}</span>
  </li>

  <li class="nav-item" *ngIf="authenticatedUser.isCustomer">
    <a routerLink="/my/profile" class="nav-link">My Profile</a>
  </li>

  <li class="nav-item" *ngIf="authenticatedUser.isAdmin">
    <a routerLink="/admin/orders" class="nav-link">All orders</a>
  </li>

  <li class="nav-link">
    <button (click)="logout()">Logout</button>
  </li>
</ng-container>

// src/ui-admin/src/identity-controls.tsx
import { useAuth } from "oidc-react";
import RenderIf from "./core/render-if";

export default function IdentityControls({}: Readonly<{
  isAuthenticated: boolean;
}>) {
  const auth = useAuth();

  const user = auth.userData?.profile;
  const isAuthenticated = user != null;

  function startOAuthLogin() {
    auth.signIn();
  }

  function logout() {
    auth.signOutRedirect();
  }

  return (
    <div className="navbar-nav ms-auto">
      <RenderIf flag={!isAuthenticated}>
        <li className="nav-link">
          <button
            className="btn btn-outline-light ms-2"
            type="button"
            onClick={startOAuthLogin}
          >
            Login
          </button>
        </li>
      </RenderIf>

      <RenderIf flag={isAuthenticated}>
        <li className="nav-link">
          <span>{user?.email}</span>
        </li>

        <li className="nav-item">
          {/* <a routerLink="/admin/orders" className="nav-link">All orders</a> */}
          <a className="nav-link">All orders</a>
        </li>

        <li className="nav-link">
          <button className="btn btn-outline-light ms-2" onClick={logout}>
            Logout
          </button>
        </li>
      </RenderIf>
    </div>
  );
}
